apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-system-custom
  namespace: argocd
  labels:
    app.kubernetes.io/name: kube-system-custom
    app.kubernetes.io/part-of: argocd
spec:
  project: default
  sources:
  - repoURL: https://raw.githubusercontent.com/kubernetes/examples/master/guestbook
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
  revisionHistoryLimit: 10
