apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: kube-system-resources
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
  - cluster-config.yaml
  - service-accounts.yaml
  - log-collector.yaml
  - cluster-monitor.yaml
  - network-policies.yaml
  - secrets.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/part-of: kube-system-apps

namespace: kube-system
