apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-operator
  namespace: kube-system
  labels:
    app.kubernetes.io/name: cluster-operator
    app.kubernetes.io/managed-by: argocd
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/EKSClusterOperatorRole  # Substitua ACCOUNT_ID
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-operator
  labels:
    app.kubernetes.io/name: cluster-operator
    app.kubernetes.io/managed-by: argocd
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-operator
  labels:
    app.kubernetes.io/name: cluster-operator
    app.kubernetes.io/managed-by: argocd
subjects:
- kind: ServiceAccount
  name: cluster-operator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-operator
  apiGroup: rbac.authorization.k8s.io
